Samplesheet validator
nf-core/demultiplex pull request #234
Opened 2024-08-08 18:38 UTC by nschcolnicov

PR created to address this issue:
https://github.com/nf-core/demultiplex/issues/222

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-08 18:39 UTC, nschcolnicov commented
PR on hold, until docker image is uploaded

2024-08-08 18:50 UTC, nschcolnicov commented on modules/local/samplesheet_validator/main.nf
> +    container "nschcolnicov/samshee:latest" //TODO replace with nf-core container
Update after creating nfcore container

2024-08-08 19:37 UTC, edmundmiller commented
A few questions for sustainability (not trying to just tear down your hardwork):
1. Is a custom Docker image required here? Could it just be an `environment.yml` and then we build the image with wave? Is `samshee` on bioconda?
2. Could this be a nf-core/module?
3. Any possibility that nf-validation or nf-schema could be used instead? Is this just a fancy way to call a json schema against the CSV?

2024-08-08 20:01 UTC, nschcolnicov commented
> A few questions for sustainability (not trying to just tear down your hardwork):
> 
> 1. Is a custom Docker image required here? Could it just be an `environment.yml` and then we build the image with wave? Is `samshee` on bioconda?
> 2. Could this be a nf-core/module?
> 3. Any possibility that nf-validation or nf-schema could be used instead? Is this just a fancy way to call a json schema against the CSV?

Hi @edmundmiller, no worries! Thank you for reviewing this changes. 

1. As far as I can tell, samshee is not available in bioconda, is this a requirement for building the image with wave? I'm not familiar with this approach.
2. This could be an nf-core module, which is why I already added some of the additional files required, in case we decide to do so.
3. What would be the benefit of having it inside the nf-validation or nf-schema? I didn't develop this tool, would it require a considerable effort to do this?

2024-08-08 20:54 UTC, nschcolnicov commented
@nf-core-bot fix linting

2024-08-08 21:20 UTC, apeltzer commented
Also chiming in here @edmundmiller  - Nicolas is working with us to get this in, as we saw there are several rules that need to be employed to verify that the Illumina samplesheets are accepted by Illumina bcl2fastq/bclconvert at least. Until now, we had several times issues where people had slight deviations from their standard (e.g. `uM` or a `(DNA/RNA) `) in their samplesheets - which took a while until the pipeline failed. 

Samshee is (though new) looking great and can do the validation of the Illumina Samplesheet very nicely. Technically maybe also feasible via nf-validation but that might take a while. We will use nf-validation to validate the *pipeline samplesheet* though.

2024-08-08 22:56 UTC, edmundmiller commented
> As far as I can tell, samshee is not available in bioconda, is this a requirement for building the image with wave? I'm not familiar with this approach. UPDATE: I replaced the docker image with wave.

Awesome, I'll add an environment.yml with what I'm talking about, and update the container and add a singularity image. 

> This could be an nf-core module, which is why I already added some of the additional files required, in case we decide to do so.

Sweet, just checking because others might find it useful.
    
> What would be the benefit of having it inside the nf-validation or nf-schema? I didn't develop this tool, would it require a considerable effort to do this?

You can talk to @maxulysse more about this one 😆 Essentially spinning up a process just to validate is slow when this could just be done with the main Nextflow process. It might also be more maintainable instead of a custom script, it could be a few lines of groovy.


@apeltzer That all sounds good, just wanted to make sure the alternatives were thought of so when someone who's a stickler for the rules comes along, I can point to a follow-up issue.

2024-08-08 23:18 UTC, edmundmiller requested changes

2024-08-08 23:18 UTC, edmundmiller commented on modules/local/samplesheet_validator/main.nf
> +    tag {"$meta.id"}
```suggestion
    tag "$meta.id"
```
Not sure if there's a reason for this instead of the usual.

2024-08-08 23:18 UTC, edmundmiller commented on modules/local/samplesheet_validator/main.nf
> +    label 'process_low'
```suggestion
    label 'process_single'
```

2024-08-08 23:18 UTC, edmundmiller commented on modules/local/samplesheet_validator/main.nf
> +    // output: //Module is meant to crash pipeline if validation fails, output is not needed
```suggestion
    output:
    // Module is meant to stop the pipeline if validation fails
    stdout
```

Maybe in the future we can handle the failure at the Nextflow level in a more elegant way instead of at the process level?

2024-08-08 23:18 UTC, edmundmiller commented on modules/local/samplesheet_validator/main.nf
> +
```suggestion
        path "versions.yml", emit: versions

```

2024-08-08 23:18 UTC, edmundmiller commented on modules/local/samplesheet_validator/main.nf
> +    exit \$status
Add a versions.yml capture here to track the versions

2024-08-09 10:03 UTC, grst commented on bin/validate_samplesheet.py
> +    validate_samplesheet(samplesheet_file, schema_file)
Just checking: Do we really need a separate python script, or is the 
command line interface
```
python -m samshee
```
already enough?

2024-08-09 10:06 UTC, grst commented
> Any possibility that nf-validation or nf-schema could be used instead? Is this just a fancy way to call a json schema against the CSV?

samshee also has some custom python code for additional validation, it does not just use a json schema. See e.g. 
https://github.com/lit-regensburg/samshee/blob/main/src/samshee/validation.py#L177

Also an illumina samplesheet contains multiple [Sections]. Samshee first parses the different sections and then applies different schemas to each of them.

2024-08-09 14:05 UTC, nschcolnicov commented on workflows/demultiplex.nf
> +    ch_validator_schema = params.validator_schema ? Channel.fromPath(params.validator_schema, checkIfExists: true) : []  // file validator_schema.json
The way it is currently implemented works just fine with multiple flow cells:
i.e test_two_lanes profile has a samplesheet that looks like this:
![image](https://github.com/user-attachments/assets/330b2b9f-9a5a-4a3c-b740-3f48f1570394)

I also generated a samplesheet by combining the test_full and test_two_lanes ones, so having three flowcells:
`id,samplesheet,lane,flowcell
SingleCell-RNA_P3,https://github.com/nf-core/test-datasets/raw/demultiplex/testdata/NextSeq2000/SampleSheet.csv,1,https://huggingface.co/datasets/nf-core/demultiplex/resolve/main/testdata/SingleCell-RNA/SingleCell-RNA_P3_2_short.tar.gz
SingleCell-RNA_P3,https://github.com/nf-core/test-datasets/raw/demultiplex/testdata/NextSeq2000/SampleSheet.csv,2,https://huggingface.co/datasets/nf-core/demultiplex/resolve/main/testdata/SingleCell-RNA/SingleCell-RNA_P3_2_short.tar.gz
35147139,https://raw.githubusercontent.com/nf-core/test-datasets/demultiplex/testdata/miseq_35147139/miseq_35147139_samplesheet.csv,1,s3://ngi-igenomes/test-data/demultiplex/miseq_35147139.tar.gz`

And it also runs as expected:
![image](https://github.com/user-attachments/assets/0730e370-d48d-447c-94db-164f8ad8de0f)

2024-08-09 14:09 UTC, nschcolnicov commented on bin/validate_samplesheet.py
> +    validate_samplesheet(samplesheet_file, schema_file)
As far as I understood the limited docs on the tool, this will simply read the sample sheet, check if there are any errors and output it again in a normalized form. But we also need to be able to provide a custom json file as validation, which I didn't find a simpler way of calling.

2024-08-09 14:11 UTC, grst commented on bin/validate_samplesheet.py
> +    validate_samplesheet(samplesheet_file, schema_file)
ok, I had hoped it might take additional arguments... too bad.

2024-08-09 14:12 UTC, grst commented on workflows/demultiplex.nf
> +    ch_validator_schema = params.validator_schema ? Channel.fromPath(params.validator_schema, checkIfExists: true) : []  // file validator_schema.json
ok, all good then!

2024-08-09 14:18 UTC, grst commented on bin/validate_samplesheet.py
> +    validate_samplesheet(samplesheet_file, schema_file)
I created a ticket: https://github.com/lit-regensburg/samshee/issues/2
Should this be implemented, we can simplify this at some later point.

2024-08-09 15:12 UTC, nschcolnicov commented
All comments were addressed, @edmundmiller could you give it a final look and see if your requested changes have been addressed?

2024-08-11 08:58 UTC, apeltzer commented
@nf-core-bot fix linting

2024-08-11 16:18 UTC, edmundmiller approved these changes
Forgot to click submit review 🫠 

Just making a follow up issue as these are nits leftover.

2024-08-12 07:02 UTC, merged

2024-08-12 07:05 UTC, apeltzer commented
Hey folks - please continue in this one here: https://github.com/nf-core/demultiplex/pull/238 as this is editable by anyone here on demux (wanted to fix linting and some smaller bits myself, I found your PR was from your fork so I couldn't edit anything...) :)