Convert stuff to DSL2
nf-core/demultiplex pull request #28
Opened 2022-04-22 20:20 UTC by Emiller88

This definitely doesn't work yet, but no reason to chase our tail until we get some test data.

Much easier to get a lay of the workflow though now.

2022-04-23 08:10 UTC, matthdsm requested changes
Perhaps it would be best to drop the QC steps and focus on the demultiplexing aspect for a first version.
So that'd mean dropping cellranger count, kraken, and fastq_screen.

2022-04-23 08:10 UTC, matthdsm commented on modules/local/bcl2fastq.nf
> +        $args2
Perhaps move this to args and only hard code in and output args

2022-04-23 08:10 UTC, matthdsm commented on modules/local/bcl2fastq.nf
> +        $args2
Perhaps move this to args and only hard code in and output args.
Also, what's the meaning of arg1 and 2 when there's only one executable?

2022-04-23 08:11 UTC, matthdsm commented on modules/local/bcl2fastq.nf
> +        --barcode-mismatches ${params.barcode_mismatches}
this is missing a `\\`

2022-04-23 14:51 UTC, Emiller88 commented
> Perhaps it would be best to drop the QC steps and focus on the demultiplexing aspect for a first version.
So that'd mean dropping cellranger count, kraken, and fastq_screen.

100%, I just wanted to split these out, so we could get a cleaner picture of what v1 looked like. Do you think we should even support bcl2fastq?

2022-04-23 15:04 UTC, Emiller88 commented on modules/local/bcl2fastq.nf
> +        $args2
I just split those up because there were so many args they wanted to handle.

2022-04-24 06:40 UTC, matthdsm commented
I'd go with `bcl-convert` and `bases2fastq` as a starting point. We can expand to `bcl2fastq`, `picard` and others in later versions as needed

2022-04-26 14:49 UTC, matthdsm commented
Feel free!

2022-04-26 15:02 UTC, merged