Adding mgikit demultiplexing
nf-core/demultiplex pull request #299
Opened 2024-12-06 03:17 UTC by ziadbkh

WIP
Closes #184

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core pipelines lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-12-06 07:58 UTC, apeltzer requested changes
That wont be enough I'm afraid

2025-02-19 16:22 UTC, apeltzer commented
Hi @ziadbkh -I'll take a look soon I hope. Do we have some test data for this to be tested via the CI entirely?

2025-02-25 23:12 UTC, ziadbkh commented
@apeltzer: Yes, there is the profile `test_mgikit' with datasets for testing and hosted online.

2025-09-18 08:22 UTC, apeltzer approved these changes
LGTM assuming that MGI Data is fine afterwards (which I cannot comment on).

2025-09-18 11:45 UTC, merged