Feature/fastp
nf-core/demultiplex pull request #38
Opened 2022-05-04 09:31 UTC by matthdsm

Added fastp qc step

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, also make a PR on the [nf-core/demultiplex branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/demultiplex)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md

2022-05-04 09:32 UTC, matthdsm commented
fixes #35

2022-05-04 09:50 UTC, matthdsm commented on workflows/demultiplex.nf
> +        return [ meta, fastq.flatten() ]
Ideally, this should merge sample meta with `fc_meta`

2022-05-04 19:07 UTC, matthdsm commented
@Emiller88 , can I get a ✅ ?

2022-05-04 20:45 UTC, Emiller88 requested changes
Awesome!

Let's just cut out the "legacy" modules, however. Those will be in the git history forever, so we don't have to keep them around. If we want to resurrect them, or pull parts out later, we can. I believe the scripts in `bin` can be removed as well.

You could also cherry-pick out those changes, we can merge this PR and then address those in a seperate PR.

2022-05-05 18:31 UTC, Emiller88 approved these changes
Awesome!

2022-05-05 18:32 UTC, merged