medium overhaul
nf-core/demultiplex pull request #45
Opened 2022-07-12 09:29 UTC by matthdsm

- Update modules
- drop input check and replace with groovy function ( fixes https://github.com/nf-core/demultiplex/issues/43)
- move bclconvert to subworkflow to emit fastq with metadata (fixes https://github.com/nf-core/demultiplex/issues/42)
- add checksums (fixes #46 )
- add test for multiple demultiplexers (fixes #47)
- add support and test for `bcl2fastq`
- linting

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-07-12 19:16 UTC, Emiller88 requested changes
I'm going to clean up the rebase of this, something still isn't right, so don't merge it yet.

2022-07-12 22:34 UTC, Emiller88 requested changes
Still have a few questions so I can be looped into the design decisions.

2022-07-12 22:34 UTC, Emiller88 commented on assets/inputs/SampleSheet.csv
> +[Header]
Should we include these? Or just leave them in nf-core/test-data?

2022-07-12 22:34 UTC, Emiller88 commented on conf/test.config
> +            ],
Should we include these by default or are they just here for example to the users?

2022-07-12 22:34 UTC, Emiller88 commented on modules/local/samplesheet_check.nf
> -}
Why are we getting rid of the nf-core convention here?

2022-07-12 22:34 UTC, Emiller88 commented on subworkflows/local/demultiplex_bclconvert/main.nf
> +        BCLCONVERT( ch_flowcell)
```suggestion
        BCLCONVERT( ch_flowcell )
```

2022-07-12 22:34 UTC, Emiller88 commented on workflows/demultiplex.nf
> +    ch_inputs = extract_csv(ch_input)
Same as above, just looking for a discussion for why we're going to stray away from the standard.

2022-07-12 22:34 UTC, Emiller88 commented on workflows/demultiplex.nf
> +    ch_raw_fastq = ch_raw_fastq.mix(BCLCONVERT.out.bclconvert_fastq)
```suggestion
    BCLCONVERT( ch_flowcells )
    ch_raw_fastq = ch_raw_fastq.mix( BCLCONVERT.out.bclconvert_fastq )
```
I'm not sure what the standard here is, we should just be consistent, but looking rnaseq, it's not perfect either.

2022-07-13 04:15 UTC, matthdsm commented on assets/inputs/SampleSheet.csv
> +[Header]
I included the samplesheets in the repo for ease of testing. Since there's no real consensus on the format yet, it's easier to have them on hand than in the test-data repo.

Once everything's more concrete, we can always move it again IMO

2022-07-13 04:18 UTC, matthdsm commented on conf/test.config
> +            ],
The structure created here makes sure no data gets overwritten in `publishDir`. When you demux by lane, you get reports with the exact same filename, so it would cause collisions.
I do suppose this is something that will have to be customised a bit for production use.

2022-07-13 04:19 UTC, matthdsm commented on modules/local/samplesheet_check.nf
> -}
I was actually following the sarek example here. They seems to skip the samplesheet check in favor of some groovy functions which seems like a good idea to me, since it's one job less to schedule.

2022-07-13 04:22 UTC, matthdsm commented on modules/local/samplesheet_check.nf
> -}
https://github.com/nf-core/sarek/blob/dev/workflows/sarek.nf#L55

2022-07-13 16:21 UTC, Emiller88 commented on conf/test.config
> +            ],
Oh, that's problematic. Not our fault, maybe we'll find a better way to handle it at the module level in the future.

For now, should this be added to `modules.config` instead of here and be a default setting?

2022-07-13 16:30 UTC, Emiller88 commented on modules/local/samplesheet_check.nf
> -}
I see, that's tempting. Sarek is the black sheep of nf-core, so I try to not use as an example, even though I also like its style. 

I think we should avoid deviating from the template to save ourselves time, and avoid messy template updates.

2022-07-13 17:09 UTC, matthdsm commented on conf/test.config
> +            ],
We could, but I think that's more up to the user to handle. We should add a big warning to the readme the file collision might happen of you run on multiple lanes

2022-07-13 17:11 UTC, matthdsm commented on modules/local/samplesheet_check.nf
> -}
🐑  Do you think you can say that to their face ?😆 
I agree with the deviating from the template part, but if we both think the groovy approach is better, shouldn't we lobby to fix the template?

2022-07-14 13:26 UTC, matthdsm commented
This is turning out to be more than some small fixes.
Reviews are welcome!

2022-09-14 23:31 UTC, Emiller88 approved these changes
Looks good, one comment on the test.config, but it's not going to break anything if we leave that, just not DRY.

2022-09-14 23:31 UTC, Emiller88 commented on conf/test.config
> +        publishDir = [
Do we have to duplicate the publishDir and when? I think they should get picked up from `modules.config`

2022-09-15 06:04 UTC, matthdsm commented on conf/test.config
> +        publishDir = [
If I don't then the options aren't picked up for some reason 😞 so the `publishDir` config reverts to the default and the  `ext.when` from the modules is ignored

2022-09-15 06:56 UTC, matthdsm commented
I'm going to go ahead and merge. Functional tests pass, we can handle the linting when we do the template update.
Any other cosmetic bugs can be fixed in another PR

2022-09-15 10:29 UTC, merged