Bases2fastq
nf-core/demultiplex pull request #51
Opened 2022-09-15 21:20 UTC by Emiller88

## PR checklist

Closes #33 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-09-15 23:26 UTC, rosibaj requested changes

2022-09-15 23:26 UTC, rosibaj commented on docs/output.md
> +[bases2fastq](https://go.elementbiosciences.com/bases2fastq-download) Demultiplexes sequencing data and converts base calls into FASTQ files for secondary analysis.
[Bases2Fastq](https://go.elementbiosciences.com/bases2fastq-download) demultiplexes sequencing data and converts base c alls generated by the Element AVITI™ System into FASTQ files for secondary analysis with FASTQ-compatible software. 

@Emiller88  It seems others provide some info on either directory location or output files; im not sure if you changes this at all from the standard b2f output.  can you include that as well?

2022-09-15 23:26 UTC, rosibaj commented on modules/nf-core/modules/bases2fastq/meta.yml
> +  - run_stats:
shoudl this instead be runstats.json? html report is twice?

2022-09-15 23:26 UTC, rosibaj commented on conf/test_b2fq.config
> +//     withName: BCLCONVERT {
why is bclconvert included with the b2f profile?

2022-09-16 05:28 UTC, matthdsm commented on subworkflows/local/input_check.nf
>      }
Please note that this subwf is deprecated and replaced in favor of a groovy function in `demultiplex.nf`

2022-09-16 05:29 UTC, matthdsm commented on nextflow.config
> +    test_b2fq { includeConfig 'conf/test_b2fq.config' }
Would it make sense to add a custom test profile for each demultiplexer? This could also solve the "hack" currently in the CI tests

2022-09-16 13:14 UTC, Emiller88 commented on nextflow.config
> +    test_b2fq { includeConfig 'conf/test_b2fq.config' }
I was going to suggest this. I think that's what I'd prefer. It's easier to keep track of then and reproduce locally. So it has my vote.

2022-09-16 13:20 UTC, Emiller88 commented on subworkflows/local/input_check.nf
>      }
Noted, did I miss something in the rebase? It seemed to just work ™️

2022-09-16 13:22 UTC, matthdsm commented on subworkflows/local/input_check.nf
>      }
I don't think you missed anything, but perhaps we're better of to remove this file to avoid confusion

2022-09-16 15:33 UTC, Emiller88 commented on subworkflows/local/input_check.nf
>      }
Hmm do you think it'll break the CI?

2022-09-16 15:34 UTC, Emiller88 commented on subworkflows/local/input_check.nf
>      }
https://github.com/nf-core/demultiplex/issues/52 made this follow up issue. I was going to scrub the change but I vote we leave it in case we need it in the future.

2022-09-16 20:02 UTC, Emiller88 commented on docs/output.md
> +[bases2fastq](https://go.elementbiosciences.com/bases2fastq-download) Demultiplexes sequencing data and converts base calls into FASTQ files for secondary analysis.
Added the table from the official docs, we've kept them the same as the standard b2f output!

2022-09-21 06:10 UTC, matthdsm approved these changes
Lookin' good!

2022-09-21 16:00 UTC, merged