Feat/wf qc options
nf-core/demultiplex pull request #70
Opened 2022-10-21 05:08 UTC by matthdsm

- add option to skip QC tools, closes #69 
- add option to skip fastq trimming, closes #68 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-10-21 15:15 UTC, Emiller88 requested changes
```
NXF_VER=21.10.3 nextflow run . -profile docker,test --outdir test --trim_fastq
```

Fails with:
```
No such variable: Exception evaluating property 'fastq' for nextflow.script.ChannelOut, Reason: groovy.lang.MissingPropertyException: No such property: fastq for class: groovyx.gpars.dataflow.DataflowBroadcast

 -- Check script './workflows/demultiplex.nf' at line: 143 or see '.nextflow.log' file for more details
 ```

2022-10-21 15:15 UTC, Emiller88 commented on conf/modules.config
> +        ext.when = {params.skip_tools && params.skip_tools.split(',').contains('fastp')}
We were having a conversation over here https://github.com/nf-core/nascent/pull/83#discussion_r1000712054

I came up with the rule:
> The config so control the configuration, not the execution logic.

We don't need to change it here, but just I just want people to start thinking about it, so we can come up with some community guidelines.

2022-10-21 20:16 UTC, matthdsm commented on conf/modules.config
> +        ext.when = {params.skip_tools && params.skip_tools.split(',').contains('fastp')}
No, I agree. The ext.when makes for a clean but unreadable workflow, so I like if statements better. I only used it here because I assumed it to be nf-core best practice

2022-10-23 18:03 UTC, Emiller88 commented on conf/modules.config
> +        ext.when = {params.skip_tools && params.skip_tools.split(',').contains('fastp')}
Nah, it's a sarek practice! :laughing:  

I think we need more use of `switch` honestly. The way you implemented that here kinda changes the readability, I find it hard in rnaseq to know when the logic stops and starts for the aligners and the branching points.

2022-10-24 06:53 UTC, matthdsm commented on conf/modules.config
> +                    params.trim_fastq ? "--settings 'R1AdapterTrim,true' --settings 'R2AdapterTrim,true'" : "",
Should we make a distinction between `b2fq` and `fastp` trimming?

2022-10-24 19:45 UTC, Emiller88 commented on conf/modules.config
> +                    params.trim_fastq ? "--settings 'R1AdapterTrim,true' --settings 'R2AdapterTrim,true'" : "",
Yeah, I just didn't know how best to flip off fastp in the case of bases2fastq, or if it was trimming more than adapters by default.

2022-10-26 10:26 UTC, matthdsm commented on conf/modules.config
> +                    params.trim_fastq ? "--settings 'R1AdapterTrim,true' --settings 'R2AdapterTrim,true'" : "",
Personally I'd say the `trim_fastq` param shouldn't have any effect on the configuration of a module, but should only affect the workflow itself (e.g, whether or not to run a step like like `fastp`).

The args for `b2fq` should be set in a custom config by the user. The fact that the module is used can be set by the `demultiplexer` param

2022-11-04 13:11 UTC, matthdsm commented
@Emiller88 , fixed the remaining issues. I think we should merge this to dev and pin a new release ASAP so we at least have a working version 😅

2022-11-23 21:49 UTC, Emiller88 commented on conf/modules.config
> +                    params.trim_fastq ? "--settings 'R1AdapterTrim,true' --settings 'R2AdapterTrim,true'" : "",
The args can be _overridden_ by the user, but I think we should have sensible defaults for how the workflow is configured.

2022-11-23 22:06 UTC, Emiller88 approved these changes
Awesome! Runs locally for me as well.

2022-11-23 22:06 UTC, merged