Sgdemux dev
nf-core/demultiplex pull request #91
Opened 2023-02-06 19:02 UTC by samfulcrum

Hello, 
This PR adds an optional demultiplexer, [sgdemux](https://github.com/Singular-Genomics/singular-demux), to nf-core/demultiplex. 

Thank you, 
Samantha

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2023-02-06 19:44 UTC, samfulcrum commented
> 

PR is no longer against `master`, now PR is into `dev`

2023-02-08 15:23 UTC, Emiller88 commented
Thanks! Could you rebase this off dev? 

```sh
git pull --rebase --autostash origin refs/head/dev
```
`origin` being the nf-core fork.

2023-02-08 15:40 UTC, Emiller88 requested changes
Looks great! Just a few prematurely cut out TODOs that we need to keep around.

Also, rebasing will get the updated CHANGELOG with the `dev` section.

Awesome work, thanks!

2023-02-08 15:40 UTC, Emiller88 commented on CHANGELOG.md
> +- [#91](https://github.com/nf-core/demultiplex/pull/91) Add sgdemux
This should be under `dev`, not the `1.0.0` release. It can be fixed while rebasing or after.

2023-02-08 15:40 UTC, Emiller88 commented on .github/workflows/awsfulltest.yml
> +        # nf-core: You can customise AWS full pipeline tests as required
```suggestion
        # TODO nf-core: You can customise AWS full pipeline tests as required
```
This still hasn't been done with bases2fastq and the Illumina software.

2023-02-08 15:40 UTC, Emiller88 commented on CITATIONS.md
> +- [sgdemux](https://github.com/Singular-Genomics/singular-demux)
There's no citation _yet_, so let's either remove this or leave a TODO to add the citation if there's going to be one.

2023-02-08 15:40 UTC, Emiller88 commented on README.md
> -
Still needs to be there, as 3/4 don't have full-sized tests.

2023-02-08 15:40 UTC, Emiller88 commented on assets/methods_description_template.yml
> -## TODO nf-core: Update the HTML below to your prefered methods description, e.g. add publication citation for this pipeline
Leave this as well, please, we haven't gotten to it.

2023-02-08 15:40 UTC, Emiller88 commented on nextflow_schema.json
> +                    "description": "Skip trimming"
Outside the scope of this PR, see #84, waiting to fix it. 

It also doesn't just skip trimming, so let's remove this.

2023-02-13 18:05 UTC, sam-white04 commented on CITATIONS.md
> +- [sgdemux](https://github.com/Singular-Genomics/singular-demux)
I cannot find any papers associated with sgdemux, nor any citation specifications so I have removed this line. @nh13 please correct me if I am wrong

2023-02-13 18:08 UTC, sam-white04 commented on CHANGELOG.md
> +- [#91](https://github.com/nf-core/demultiplex/pull/91) Add sgdemux
Resolved in commit [d381531](https://github.com/fulcrumgenomics/nfcore-demultiplex/commit/d381531c62489fd486fec7d153e92e72baede6c5)

2023-02-13 18:08 UTC, sam-white04 commented on CITATIONS.md
> +- [sgdemux](https://github.com/Singular-Genomics/singular-demux)
Removed citation in [d381531](https://github.com/fulcrumgenomics/nfcore-demultiplex/commit/d381531c62489fd486fec7d153e92e72baede6c5)

2023-02-13 18:14 UTC, sam-white04 commented on README.md
> -
Re-placed TODO in commit [0923812](https://github.com/fulcrumgenomics/nfcore-demultiplex/commit/0923812a5c9e44b212b0c4a761c10ddbc4d858bf)

2023-02-13 18:14 UTC, sam-white04 commented on assets/methods_description_template.yml
> -## TODO nf-core: Update the HTML below to your prefered methods description, e.g. add publication citation for this pipeline
Re=placed TODO in commit [0923812](https://github.com/fulcrumgenomics/nfcore-demultiplex/commit/0923812a5c9e44b212b0c4a761c10ddbc4d858bf)

2023-02-13 18:14 UTC, sam-white04 commented on nextflow_schema.json
> +                    "description": "Skip trimming"
Resolved in commit [0923812](https://github.com/fulcrumgenomics/nfcore-demultiplex/commit/0923812a5c9e44b212b0c4a761c10ddbc4d858bf)

2023-02-14 17:03 UTC, sam-white04 commented
> Thanks! Could you rebase this off dev?
> 
> ```shell
> git pull --rebase --autostash origin refs/head/dev
> ```
> 
> `origin` being the nf-core fork.

Successfully rebased @Emiller88

2023-02-14 17:09 UTC, Emiller88 requested changes
Just need to get the changelog right, and we'll see if the CI passes!

2023-02-14 17:09 UTC, Emiller88 commented on CHANGELOG.md
> +- [#91](https://github.com/nf-core/demultiplex/pull/91) Add sgdemux
This should be under `dev`, 1.1.0 has already been released, and this will go out in 1.2.0

2023-02-14 17:30 UTC, sam-white04 commented on CHANGELOG.md
> +- [#91](https://github.com/nf-core/demultiplex/pull/91) Add sgdemux
@Emiller88 I changed that previously... 34dd515fa2eef377f240b5d96c0c96ab70de0fe1. I will update again

2023-02-14 18:01 UTC, nh13 commented
@nf-core-bot fix linting

2023-02-14 18:39 UTC, Emiller88 approved these changes
Sweet, I think this looks good code wise! I'm relying on y'all to make sure it works as expected otherwise.

2023-02-14 18:42 UTC, Emiller88 commented
You also might add yourselves to the README! https://github.com/nf-core/demultiplex#credits

I'll make a PR to add a CODEOWNERS file as well(#88)

2023-02-14 18:42 UTC, sam-white04 commented on tests/pipeline/default/sgdemux.nf.test
> +    name "Test SGDEMUX"
```suggestion
    name "Test sgdemux"
```

2023-02-14 21:28 UTC, merged