fqtk additional tool
nf-core/demultiplex pull request #99
Opened 2023-03-08 16:19 UTC by sam-white04

Hello, 

I have added [fqtk](https://github.com/fulcrumgenomics/fqtk) as an optional demultiplexer. The tool fqtk requires an additional input to be provided as a path in the 5th column of `--input samplesheet.csv`.  

Thank you, 
Samantha White

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)- [x] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated. (@sam-white04 Will update as soon as PR is posted)
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2023-03-08 17:04 UTC, Emiller88 commented
I think all of your commits got squashed 🙃

2023-03-08 17:21 UTC, sam-white04 commented
These checks passed locally. So let me do some digging to fix this.

2023-03-15 00:25 UTC, Emiller88 requested changes
Few small comments and style changes, but looks pretty good!

2023-03-15 00:25 UTC, Emiller88 commented on README.md
> +4. FASTQ files with user supplied read structures (via ['fqtk'](https://github.com/fulcrumgenomics/fqtk))
```suggestion
4. FASTQ files with user supplied read structures (via [`fqtk`](https://github.com/fulcrumgenomics/fqtk))
```

2023-03-15 00:25 UTC, Emiller88 commented on subworkflows/local/fqtk_demultiplex/main.nf
> +include {CSV2TSV} from "../../../modules/local/csv2tsv"
```suggestion
include { CSV2TSV } from "../../../modules/local/csv2tsv"
```

2023-03-15 00:25 UTC, Emiller88 commented on subworkflows/local/fqtk_demultiplex/main.nf
> +    rg.PL = "SINGULAR"
Should this be hard-coded?

2023-03-15 00:25 UTC, Emiller88 commented on workflows/demultiplex.nf
> +            }
Could we put this inside of the switch case for fqtk instead? Maybe turn it into a subworkflow? Possibly turn them both into a subworkflow?

2023-03-15 00:25 UTC, Emiller88 commented on workflows/demultiplex.nf
> +}
These are starting to get excessive. @matthdsm what happens if we put them in `lib/`? Would they still work the same?

2023-03-15 15:04 UTC, sam-white04 reviewed
@Emiller88 Thank you for your comments. If everyone is on the same page, Im happy to pull the generation of `ch_flowcells` and `ch_flowcells_tar` into subworkflows for fqtk vs the other demultiplexers.

2023-03-15 15:04 UTC, sam-white04 commented on workflows/demultiplex.nf
> +            }
@Emiller88 I agree this gets a bit messy, Im happy to pull both into subworkflows where the input is `ch_input` and the output is `ch_flowcells` and `ch_flowcells_tar`. Thoughts?

2023-03-15 15:04 UTC, sam-white04 commented on workflows/demultiplex.nf
> +}
@Emiller88 Moving the prep for `ch_flowcells` into subworkflows would remove the need for these functions to be in `demultiplex.nf`, right?

2023-03-15 16:20 UTC, Emiller88 commented on subworkflows/local/fqtk_demultiplex/main.nf
> +    rg.PL = "SINGULAR"
There might be a way to read in the read group. We can just throw a TODO on it though for now.

2023-03-15 16:22 UTC, Emiller88 commented on workflows/demultiplex.nf
> +}
Right, that's a great idea!

2023-03-15 16:23 UTC, Emiller88 approved these changes
I think this looks good to me. #102 For follow up to clean up some things that needed to be introduced here.

2023-03-16 06:59 UTC, matthdsm commented on workflows/demultiplex.nf
> +}
I've no qualms putting all the functions in `/lib`. They're only in the main file for convenience!

2023-03-16 06:59 UTC, matthdsm approved these changes

2023-03-16 17:04 UTC, merged